//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaptureLibrary.Kinect {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class CalibrationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CalibrationSettings defaultInstance = ((CalibrationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CalibrationSettings())));
        
        public static CalibrationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public float MinZ {
            get {
                return ((float)(this["MinZ"]));
            }
            set {
                this["MinZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float MaxZ {
            get {
                return ((float)(this["MaxZ"]));
            }
            set {
                this["MaxZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float MaxY {
            get {
                return ((float)(this["MaxY"]));
            }
            set {
                this["MaxY"] = value;
            }
        }
    }
}
